# yaml-language-server: $schema=./config.schema.json

app:
  # ------------------------------------------------------------------
  # Application identity (provided by Primus Labs)
  # ------------------------------------------------------------------
  identity:
    userToken: "<YOUR_TOKEN>"
    projectId: "<YOUR_PROJECT_ID>"

  # ------------------------------------------------------------------
  # Blockchain configuration
  # ------------------------------------------------------------------
  blockchain:
    network: base # base | base-sepolia

    # Required only if subscription type is PLAN_SELF_PAID
    signer:
      privateKey: "<PRIVATE_KEY>"

# --------------------------------------------------------------------
# Data source configurations
# At least one datasource must be configured: binance or aster
# --------------------------------------------------------------------
datasource:
  binance:
    # Binance account #1
    - apiKey: "binance-key-123"
      apiSecret: "binance-secret-abc"
      kind: ["spot", "usds-futures"] # spot | usds-futures | coin-futures | unified | margin

    # Binance account #2 (disabled by set enabled to false)
    - apiKey: "binance-key-456"
      apiSecret: "binance-secret-def"
      kind: ["spot", "unified"]
      enabled: false # optional, default: true
      description: "My Binance spot account" # optional, default: ""

  aster:
    - apiKey: "aster-key-123"
      apiSecret: "aster-secret-abc"
      kind: ["spot", "usds-futures"] # spot | usds-futures
